apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cargolytics

resources:
- service.yaml

bases:
- ../base
namespace: cargolytics-dev

images:
- name: myimage
# - configMap.yaml